AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'test/**/*'
  TargetRubyVersion: 2.6.4

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
